### ISSUE TITLE
Fontes

### ISSUE THREAD

**Issue by acggermed** [ranieresilva/controle-estoque#12]
Olá amigo, parabéns pela competência...
Por favor me orienta como baixar esses fontes completos do controle de estoque...

Grato

Antonio Carlos

**Comment by acggermed** [comment]
Consegui baixar...

**Comment by Nokard** [comment]
Show de bola amigo,

**Comment by ranieresilva** [comment]
excelente! lembrando que os fontes estão aqui por episódio do canal no YouTube, sendo que cada branch corresponde a um episódio.
