### ISSUE TITLE
Rotativa.dll

### ISSUE THREAD

**Issue by acggermed** [ranieresilva/controle-estoque#13]
Olá, consegui baixar o estoque, porém ao rodar pelo VS da erro na Rotativa.dll dentro da pastas Totativa\bin\Debug...  não veio esa dll, nem a pasta

**Comment by ranieresilva** [comment]
opa! então, o pacote Rotativa é um que deve ser obtido a parte, como um projeto. Recomendo baixar de https://github.com/webgio/Rotativa
